INSERT INTO PARENT_ENTITY(PARENT_ID)
                   VALUES(NEXTVAL('SEQ_PARENT_ID'));

INSERT INTO CHILD_ENTITY(CHILD_ID,                PARENT_ID)
                  VALUES(NEXTVAL('SEQ_CHILD_ID'), CURRVAL('SEQ_PARENT_ID'));

INSERT INTO CHILD_ENTITY(CHILD_ID,                PARENT_ID)
                  VALUES(NEXTVAL('SEQ_CHILD_ID'), CURRVAL('SEQ_PARENT_ID'));

INSERT INTO CHILD_ENTITY(CHILD_ID,                PARENT_ID)
                  VALUES(NEXTVAL('SEQ_CHILD_ID'), CURRVAL('SEQ_PARENT_ID'));