
DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
  ID INTEGER NOT NULL,
  LOCAL_DATE_TIME TIMESTAMP(9) WITHOUT TIME ZONE,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ARTICLE;
CREATE TABLE ARTICLE (
  ID INTEGER NOT NULL,
  LOCAL_TIME TIME(9),
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT (
  ID INTEGER NOT NULL,
  OFFSET_DATE_TIME TIMESTAMP(9) WITH TIME ZONE,
  PRIMARY KEY (ID)
);